// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajvopfasvueskdcmfnub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqdm9wZmFzdnVlc2tkY21mbnViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDgzNDEsImV4cCI6MjA1OTAyNDM0MX0.lHQ9MgnNqpf-r8IaAOMns-RLXnm1KxO4LJbgRcWeaBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);